# Generated by Django 5.2.8 on 2025-12-01 15:00

import concess.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concessionnaire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='concessionnaire',
            name='siret',
            field=models.CharField(max_length=14, validators=[concess.models.validate_siret]),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='concessionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='concess.concessionnaire'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type',
            field=models.CharField(choices=[('moto', 'moto'), ('auto', 'auto')], max_length=10),
        ),
    ]
